experiment_tracking:
  experiment_name: sphereface2-training-test
  experiment_description: 'sphereface2 training test with sagemalker'
  run_name: sphereface2-training-test
  run_description: 'run description'

execution:
  base_image: '249265253269.dkr.ecr.eu-west-1.amazonaws.com/cv-ml-model-training:emotion_classifier-tensorflow-2.10-py39-v1.1.0'
  # instance_type: 'ml.g5.12xlarge'
  instance_type: 'ml.g4dn.12xlarge'
  # instance_type: 'ml.m5.large'
  instance_count: 1

project:
  proj_dir: project/
  model_dir: models/
  cfg_fname: config.yml
  train_log:
    path: train.log
    screen_intvl: 200
    headers: {Loss: ':3.4f', bkb_grad: ':3.2f', head_grad: ':3.2f',
      Mag_mean: ':3.2f', Mag_std: ':3.2f'}
  val_log:
    path: val.log
    screen_intvl: 1
    # headers: {LFW: ':3.3f', AgeDB-30: ':3.3f', CA-LFW: ':3.3f',
    #   CP-LFW: ':3.3f'}
    headers: {LFW: ':3.3f'}
  val_intvl: 200
  save_iters: [10, 96000, 97000, 98000, 99000, 100000]
data:
  base:
    dataset:
      type: PairDataset
      test_mode: true
    dataloader: {type: DataLoader, batch_size: 64,
      shuffle: false, drop_last: false, num_workers: 4,
      pin_memory: true}
  train:
    dataset:
      type: ClassDataset
      name: VGGFace2
      data_dir: s3://cv-ml-face-recognition/data/opensphere_data/vggface2_small/
      ann_file: vggface2_train_ann.txt
      test_mode: false
    dataloader: {batch_size: 512, shuffle: true, drop_last: true}
  val:
  - dataset:
      name: LFW
      data_dir: s3://cv-ml-face-recognition/data/opensphere_data/lfw/
      ann_file: lfw_ann.txt
      metrics:
      - ACC
  # - dataset:
  #     name: AgeDB-30
  #     ann_file: agedb_30_ann.txt
  #     metrics:
  #     - ACC
  # - dataset:
  #     name: CA-LFW
  #     ann_file: calfw_ann.txt
  #     metrics:
  #     - ACC
  # - dataset:
  #     name: CP-LFW
  #     ann_file: cplfw_ann.txt
  #     metrics:
  #     - ACC
parallel:
  backend: nccl
  dist_url: tcp://127.0.0.1:21119
  device_ids: [0, 1, 2, 3]
model:
  base:
    net: {}
    optimizer: {type: SGD, lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    scheduler:
      type: MultiStepLR
      milestones: [50000, 78000, 94000, 100000]
      gamma: 0.1
  backbone:
    net:
      type: sfnet20_deprecated
      in_channel: 3
      channels: [64, 128, 256, 512]
      out_channel: 512
  head:
    net:
      type: SphereFace2
      magn_type: C
      alpha: 0.7
      r: 40
      m: 0.4
      t: 3.0
      lw: 10.
